# Generated by Django 4.2.30 on 2026-04-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('holes_played', models.CharField(choices=[('front9', 'Front 9'), ('back9', 'Back 9'), ('full18', 'Full 18')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strokes', models.IntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rounds.round')),
            ],
        ),
    ]
