# Generated by Django 4.2.30 on 2026-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='st-andrews', unique=True),
            preserve_default=False,
        ),
    ]
